name: Development And Unit Test Pipeline

on:
  push:
    branches:
      - 'dev*'

jobs:
  build-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Run project commands
        run: |
          apt update -y
          apt install npm -y
          npm install

  deploy-pipeline:
    runs-on: ubuntu-latest
    needs: build-pipeline
    strategy:
      max-parallel: 1
    
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Run project commands
        run: |
          apt update -y
          apt install npm -y
          npm install
          apt install nodejs -y
          node index.js
